### ISSUE TITLE
Svls does not work with svlint special comments

### ISSUE THREAD

**Issue by supleed2** [dalance/svls#147]
It seems that the special comments added to svlint in dalance/svlint#114 do not work when using [svls-vscode](https://github.com/dalance/svls-vscode).
I don't see any reason why the language client extension would skip comments so my guess is that the special comments from svlint are just unused within svls?
![image](https://user-images.githubusercontent.com/21363892/168035655-d17223d8-beeb-465e-9d3a-0ec8a16e4087.png)

**Comment by dalance** [comment]
The function of control comment was implemented at the svlint specific logic.
I fixed it, and released svls v0.2.2.
