### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by prokie** [dalance/svls#148]
Hello.

Trying to install this using `cargo install svls` but it get stuck at ` Building [=======================> ] 194/195: svls(bin)`. 

Windows 11
rustc version 1.61.0
rustup version 1.24.3

**Comment by DaveMcEwan** [comment]
Did you let it finish building? Windows builds are known to be very slow.

**Comment by prokie** [comment]
Yes, that was the issue. I did not realize that it would be that slow.
