### ISSUE TITLE
Update to newer tower-lsp

### ISSUE THREAD

**Issue by ebkalderon** [dalance/svls#3]
Author of `tower-lsp` here! I just wanted to let you know that `tower-lsp` has been rapidly improving over the past several months and has seen a great many improvements since 0.4.1. Among other things, it has gained:

* Support for `std::future::Future`, the newest `tokio`, and async/await.
* Support for a crap-ton more LSP requests, [almost supporting all of LSP 3.15](https://github.com/ebkalderon/tower-lsp/issues/10).
* Support for all server-to-client requests, renaming `Printer` to [`Client`](https://docs.rs/tower-lsp/0.9.0/tower_lsp/struct.Client.html).
* `LanguageServer` trait methods are no longer required, except for `initialize` and `shutdown`.
* Notification trait methods are now `async fn`.
* You can now call `.await` on `serve()` directly, eliminating the need for `ExitReceiver`.
* Backpressure is now handled properly.

If you would like to port your server to async/await and add some new features to your SystemVerilog server, such as goto declaration, goto definition, goto type definition, code formatting, document symbols, references, etc. [0.9.0 has just been published to Crates.io](https://crates.io/crates/tower-lsp).

**Comment by dalance** [comment]
Thank you for your information!
I updated tower-lsp to 0.9.

**Comment by ebkalderon** [comment]
Awesome! :tada: I'm glad the migration was successful, and I hope you continue to expand your language server in the future. As always, feel free to report any bugs or other issues you find. I'll try my best to respond as soon possible.

**Comment by ebkalderon** [comment]
Closing, as the update has been addressed in 24b5737.
