### ISSUE TITLE
Question about VSCODE

### ISSUE THREAD

**Issue by nikhenri** [dalance/svls#30]
Hi!

I'm using SVLS-vscode on VSCODE.
It seem to work but I realize that any error I have is only display as parse error at the top of the module declaration.
![image](https://user-images.githubusercontent.com/61157967/103030819-8eb37280-452a-11eb-8de6-7ddba5fea4c7.png)
Is this the expected beahvior ? Is it supose to show me the line in error ?

Thank you for your help :)

Info about my setup:
![image](https://user-images.githubusercontent.com/61157967/103031053-16997c80-452b-11eb-85cc-986aff07312e.png)

**Comment by dalance** [comment]
Thank you for your report.
I fixed this issue, and released v0.1.19.

**Comment by nikhenri** [comment]
Thank you for the quick answer, I just install the latest version and now the error is reported at the **_always_**, which is very nice.
![image](https://user-images.githubusercontent.com/61157967/103549809-f2686480-4e75-11eb-91f7-9faa97c957b0.png)

Still I wonder, is it the expected behavior? Or should it mark the exact line in error ?
Thank you

**Comment by dalance** [comment]
I fixed it, and released v0.1.20.
Now error will be reported at the next item of missing `;`.

**Comment by nikhenri** [comment]
Thank you :) it work perfectly
