### ISSUE TITLE
False error report for Array length declaration using length

### ISSUE THREAD

**Issue by nikhenri** [dalance/svls#34]
Hi,
When creating an array using the length [int] instead of a range [int:int], svls report an parse error:
![image](https://user-images.githubusercontent.com/61157967/103552979-c4395380-4e7a-11eb-930b-98f9a096c691.png)

Thank you :)

**Comment by dalance** [comment]
`logic [4] foo` is invalid syntax.
`[]` before identifier should be `packed_dimension` like `[3:0]` in language specification.
(`unpacked_dimension` like `[4]` can be used after identifier only)

Some tools can accept this syntax, but some tools can't.
So I recommend to follow language specification.

**Comment by nikhenri** [comment]
Well it's part of the IEEE STD since 2005

![image](https://user-images.githubusercontent.com/61157967/103675157-98d36900-4f4d-11eb-8bf2-b72a67a08c43.png)

I'm not sure it's should be declare as an error because some tools doesn't support it, I think it should just check with the IEEE std.
What do you think ?

**Comment by nikhenri** [comment]
After verification, I realize that you are right, this only apply to unpack array (It's a bit confusing).
Thank you
