### ISSUE TITLE
Question about the rule 'non_ansi_module'

### ISSUE THREAD

**Issue by nikhenri** [dalance/svls#37]
Hi,
When writing a TestBench I always got the **non_ansi_module** since I have no port.
![image](https://user-images.githubusercontent.com/61157967/103897598-cfca8b80-50c1-11eb-9939-d2cdeb6ffbe4.png)

Do you think it would make sense to not apply this rule check when no port are declared ?

I could add a dummy input to remove the warning but that a bit weird :/
![image](https://user-images.githubusercontent.com/61157967/103898171-8dee1500-50c2-11eb-8874-34c687551933.png)

What do you think ?

Thank you

**Comment by dalance** [comment]
Thanks!
I think this is misjudgment.
I fixed and released v0.1.21.
