### ISSUE TITLE
Parse error with import

### ISSUE THREAD

**Issue by eunchan** [dalance/svls#8]
Hi,

I am seeing a "parse error" on the module that uses `import` in the module header.

![Screen Shot 2020-10-19 at 2 01 59 PM](https://user-images.githubusercontent.com/1192814/96511262-b11bcd80-1213-11eb-9afb-3870e66348c5.png)

I've run `svlint` with the config I use and proper `--incdir` option but svlint doesn't show the same error.

**Comment by dalance** [comment]
Thank you for your report.
Could you provide the version information of `svls` and `svlint` and the sample source code to reproduce it?
